[project]
name = "hoops-sim-engine"
version = "0.1.0"
description = "Add your description here"
author = "Ben Espinoza"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[dependency-groups]
dev = [
    "ruff>=0.14.9",
]
